spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audio_book
    username: postgres
    password: root123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update